apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-mysql
  namespace: python-demo
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/mysql-data"
