version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=training-2023
      - MYSQL_DATABASE=users
      - MYSQL_USER={MYSQL_USER}
      - MYSQL_PASSWORD={MYSQL_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - app-network

  nodejs-app:
    image: namnguyen96/demo-devops:{TAG}
    restart: always
    build:
      context: nodejs/.
      dockerfile: Dockerfile
    container_name: nodejs-app
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      - MYSQL_USER={MYSQL_USER}
      - MYSQL_PASSWORD={MYSQL_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    external: true
