apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-jenkins
  namespace: nodejs-demo
  labels:
    type: local
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ubuntu/data/jenkins_home/
