apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: nodejs-demo
spec:
  volumeName: api-jenkins
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
