apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: nodejs-demo
spec:
  ports:
    - port: 8080
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
  selector:
    app: jenkins
